# Datos Categoricos

* Tenemos 2 tipos de datos: númericos y categoricos
* Dato categoricos: país en el que nacemos, tipo de sangre etc.
* Para el aprendizaje de máquinas estos datos pueden ser un reto.
* Tenemos que hacer una transformación para cambiar estos datos a númericos, ya que por ejemplos las redes neuronales utilizan estos datos.

In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

### Contexto y Datos Categóricos

In [5]:
datos = {
    "nombre": ["Mariana", "Ana", "Elsa", "Gustavo", "Pedro", "Raul", "Carlos", "José", "Luis"],
    "saldo": [10000.00, 8000.00, 9000.00, 2000.00, 2100.00, 12000.00, 5000.00, 10000.00, 200.00],
    "pais": ["Argentina", "Bolivia", "Chile", "Colombia", "Costa Rica", "Ecuador", "Mexico", "Peru", "Peru"]
}

datos = pd.DataFrame(datos)

# Cambiamos el tipo de datos de object a Category
datos["pais"] = datos["pais"].astype("category")
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  9 non-null      object
 1   saldo   9 non-null      float64
 2   pais    9 non-null      category
dtypes: category(1), float64(1), object(1)
memory usage: 649.0+ bytes

### Inapropiada Codificación con Reemplazo

* Con estos valores, la máquina podría tomarlos como proximidad entre paises o referencia a su tamaño, población etc.
* Esto no se debe hacer y podríamos meter un sesgo a nuestra información.

In [8]:
datos_sesgados = datos.copy()
reemplazos = {
    "Argentina":1, 
    "Bolivia":2,
    "Chile":3, 
    "Colombia":4, 
    "Costa Rica":5, 
    "Ecuador":6, 
    "Mexico":7, 
    "Peru":8
}
# Esto para los datos que no son category
#datos_sesgados["pais"].replace(reemplazos)
datos_sesgados["pais"] = datos_sesgados["pais"].cat.rename_categories(reemplazos)
datos_sesgados

    nombre    saldo pais
0  Mariana  10000.0    1
1      Ana   8000.0    2
2     Elsa   9000.0    3
3  Gustavo   2000.0    4
4    Pedro   2100.0    5
5     Raul  12000.0    6
6   Carlos   5000.0    7
7     José  10000.0    8
8     Luis    200.0    8

### Codificación de Categorías One-Hot

* El primer 1 nos esta indicando que el primer objeto pertenece a Argentina
* El segundo 1, también hace referencia a otros país.
* Al final vemos que perú venía 2 veces, por lo que podemos ver doble 1 en la columna para Peru.
* Filas = clientes, Columna=Pais
* El 1 hace referencia a que esta encendido.

In [14]:
codificador = OneHotEncoder()
codificacion = codificador.fit_transform(datos[["pais"]])
print(type(codificacion))
print(codificacion)
print(codificacion.toarray())

nuevas_cols = pd.DataFrame(codificacion.toarray(),
                          columns=codificador.categories_)
print(nuevas_cols)
datos = pd.concat(
    [datos,nuevas_cols],
    axis="columns"
)
datos

<class 'scipy.sparse._csr.csr_matrix'>
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 7)	1.0
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
  Argentina Bolivia Chile Colombia Costa Rica Ecuador Mexico Peru
0       1.0     0.0   0.0      0.0        0.0     0.0    0.0  0.0
1       0.0     1.0   0.0      0.0        0.0     0.0    0.0  0.0
2       0.0     0.0   1.0      0.0        0.0     0.0    0.0  0.0
3       0.0     0.0   0.0      1.0        0.0     0.0    0.0  0.0
4       0.0     0.0   0.0      0.0        1.0     0.0    0.0  0.0
5       0.0     0.0   0.0      0.0        0.0     1.0    0.0  0.0
6       0.0     0.0   0.0      0.0        0.0     0.0    1.0  0.0
7       0.0     0.0   0.0      0.0        0.0     0.0    0.0  1.0
8       0.0     0.0   0.0      0.0        0.0     0.0    0.0  1.0

,nombre,saldo,pais,"(Argentina,)","(Bolivia,)","(Chile,)","(Colombia,)","(Costa Rica,)","(Ecuador,)","(Mexico,)","(Peru,)"
0,Mariana,10000.0,Argentina,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ana,8000.0,Bolivia,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Elsa,9000.0,Chile,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,Gustavo,2000.0,Colombia,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Pedro,2100.0,Costa Rica,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,Raul,12000.0,Ecuador,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,Carlos,5000.0,Mexico,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,José,10000.0,Peru,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,Luis,200.0,Peru,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
datos.drop("pais", axis="columns", inplace=True)
datos

,nombre,saldo,"(Argentina,)","(Bolivia,)","(Chile,)","(Colombia,)","(Costa Rica,)","(Ecuador,)","(Mexico,)","(Peru,)"
0,Mariana,10000.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ana,8000.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Elsa,9000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,Gustavo,2000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Pedro,2100.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,Raul,12000.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,Carlos,5000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,José,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,Luis,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0